### ISSUE TITLE
Setup automated builds with Docker Hub registry for faster deploy

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#11]

**Comment by PenguinSnail** [comment]
Automated builds now occur at [https://hub.docker.com/r/team1533/](https://hub.docker.com/r/team1533/) with _latest_ building from `master` and _production_ building from `prod`

The images are not yet pulled in the docker-compose file, and will probably not be used for latest as they take a significant amount of time to build.

**Comment by aidanh010** [comment]
Nice work, concur that they shouldn't be in the docker compose file. If we want to tell people to use this we can just dump a modified one in a gist or a separate file.

**Comment by PenguinSnail** [comment]
README has been updated on how to use an additional docker-compose file has been added that will build with the pre-built images from the production branch
