### ISSUE TITLE
Report version to end user in JScout

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#17]
To help with caching issues.
JScout version would be internal (package file -- which we should probably be updating?), GoScout would presumable via read API. Or we could go a different route and have the whole thing determined by an `.env` setting or (ideally) the git commit of the tree it was built from. We should be able to do that last option easily in the Dockerfile for JScout, and as long as we always used Compose/built both images at the same time, we wouldn't have to worry about GoScout version.

**Comment by aidanh010** [comment]
https://blog.alexellis.io/inject-build-time-vars-golang/ (if we *always* build with Compose we could just choose whether doing this in JScout or GoScout is easier, but it would be best to do both). Either way, this can be made more useful by including a button to [clear the page cache, especially useful on mobile](https://stackoverflow.com/questions/1011605/clear-the-cache-in-javascript) as is found on Wikipedia.

Also, we should do the same with Docker images for easy version checking from command line: https://container-solutions.com/tagging-docker-images-the-right-way/

**Comment by PenguinSnail** [comment]
Caching issues have been solved via the new service worker
