### ISSUE TITLE
Browser returns garbled/blank response text for HTTP 201 from GoScout on successful submit of new record

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#18]
**Describe the bug**
Instead of the string passed from GoScout error handling code introduced in #16, web browsers accessing JScout show a JavaScript alert showing only the status number and code, not the string in the response body. Other codes such as `500`, `502`, `409` work as expected.

**To Reproduce**

- Trigger an `HTTP 201 CREATED` response by successfully submitting match or pit data.

**Expected behavior**
Should pass on the response as received in `xhr.responseBody` as it does for `500` and `409` errors. GoScout writes this for these errors using the `http.Error()` call, which takes a string to write as response body. The current code, since `201` is not an error proper, uses the following (although the same behavior has been confirmed when using `http.Error` with code 200. This runs the exact same code as `409` JScout-side since the branch in commit b6a61e4142 (PR #16) evaluates using the condition `(xhr.status <= 299 || xhr.status == 409)`.

GoScout writing response message:
```go
w.WriteHeader(201)
w.Write(byte[]("message literal"))
```

JScout handling:
```typescript
    xhr.onreadystatechange = function() {
      //Call a function when the state changes.
      if (xhr.readyState == XMLHttpRequest.DONE && (xhr.status <= 299 || xhr.status == 409)) {
        // Clear form. Data is either recorded or duplicate.
        (<HTMLFormElement>document.getElementById("matchForm")).reset();
        alert(`Message from server: ${xhr.status} ${xhr.statusText} -- ${xhr.responseText}`);
      } else if (xhr.readyState == XMLHttpRequest.DONE && xhr.status >= 300) {
        // Don't clear form. 
        alert(`Message from server: ${xhr.status} ${xhr.statusText} -- ${xhr.responseText}`);
      }
}
```

**Screenshots (highly appreciated)**
![201_error_garbled](https://user-images.githubusercontent.com/20847468/42727017-69758b1c-876c-11e8-816b-58768d80fc88.PNG)
![201_edge_case](https://user-images.githubusercontent.com/20847468/42727015-671b18be-876c-11e8-9c0f-623ad306194d.PNG)
![img_1401](https://user-images.githubusercontent.com/20847468/42727030-9488bea0-876c-11e8-960f-43d3fd7bfea6.PNG)

**Your Specs (please complete the following information):**
 - **Renders Garbled:** Firefox Nightly 63.0a1 (2018-07-12) (64-bit)
 - **Renders Blank:** Microsoft Edge 42.17134.1.0 (Microsoft EdgeHTML 17.17134), iOS Safari (iOS 12.0 dev beta 3)

**Additional context**
*Thoughts: encoding is probably set wrong somewhere, but the test using `http.Error()` should have ruled that out.*

**Comment by aidanh010** [comment]
Interestingly, fixing the regression in #19 resulted in the pit form not only working (displaying user feedback and clearing form), but now displaying the `201` correctly. No effect on match form ofc, but the regression was simply forgetting to update a variable in copying code *from* the match form...

**Comment by PenguinSnail** [comment]
Leaving this here to refer back if needed:
[https://golang.org/src/net/http/server.go#L1956](https://golang.org/src/net/http/server.go#L1956)
