### ISSUE TITLE
Implement self-service JScout CSV export

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#24]
**What parts of the StrangeScout system does this involve?**
Could be done entirely in JScout through a generic CRUD API in GoScout, or could be done via a special endpoint in GoScout.

**Is your feature request related to a problem? Please describe.**
Partner teams express concern over availability of SQL exports, a schedule/plan for which is often lacking and as such an unexpected amount of developer time is spent cleaning and preparing CSV exports in DBeaver. Thanks to hard duplicate rejection in #13, this process should be a lot shorter, but having a CSV export is still way better.

**Describe the solution you'd like**
Develop a simple button that can return a CSV download of entire database contents, possibly with event filters. Not designed for analytics, filtering, etc., just for any end user to be able to import into COTS analytics software or simply view the raw data.

**Describe alternatives you've considered**
Would probably be best to handle JScout side, but if the GoScout ORM (#20) is truly as easy to code with as claimed, it might be easiest to do it there. Would certainly rather do Serialize-Deserialize in Go than JS.

**Additional context**
Along with #25, this enables "admin-less" operation with no direct SQL access, always a nice feature to be able to fall back on. This does come with the downside that data theft, as well as spamming, is now a threat. However, user management is on the roadmap for v1.0 so that shouldn't be an issue.

**Comment by PenguinSnail** [comment]
CSV exports are now available for record queries. Simply append `?format=csv` to the query path and a file will be downloaded. This is available for the two main read queries, individual runs and all runs performed by a team.

For example: `/api/event/turing/team/1533/all?format=csv` would return a CSV of all team **1533**'s runs at the **turing** event
