### ISSUE TITLE
Dockerize GoScout and add to repo

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#4]
Make sure that ALL user-specific and secure data is in environment variables to be controlled by Docker Compose! Not committed to GitHub!

**Comment by aidanh010** [comment]
GoScout will be replaced by a new bakend written in Rust, so there is no point in Dockerizing it. If needed we can clone old GoScout repo for IRI.

Reason: google.com/search?q=go+vendoring
google.com/search?q=go+outside+of+go+path

**Comment by PenguinSnail** [comment]
go path isn't really an issue and we shouldn't abandon GoScout just yet.
GoScout has been successfully dockerized in the repo as well as uses build arguments to hide sensitive logon info for the database server.

**Comment by aidanh010** [comment]
See #9

**Comment by aidanh010** [comment]
fixed as part of #13, won't bother redacting old info as its no longer in use
