### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by PenguinSnail** [triplestrange/StrangeScout#63]
### Admin Panel Features
- [x] New User
- [x] New Admin
~- [x] Auth Cookie Timeout~
- [ ] User Deletion
- [ ] User Password Resets
- [ ] Scouting Database Reset
---
~- [ ] StrangeBox Sync (*Requires StrangeBox #61 to be completed beforehand*)~

**Comment by PenguinSnail** [comment]
Initial features implemented in #62

**Comment by PenguinSnail** [comment]
Database replication can be configured live and persistently therefore we no longer need a sync action in the admin panel

**Comment by aidanh010** [comment]
Ok, I'm going to mark this as done for W1 punchlist. It might still be nice to support adding those sync relationships via the GUI later but it's not critical.

**Comment by PenguinSnail** [comment]
Marking closed as we don't really need any new features in the panel currently
