### ISSUE TITLE
Manage HTTPS in Express

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#66]
Express should be serving SSL. This should be done as a commandline option or something simple, warn if nothing is chosen. Only reason to use HTTP is if you're behind a reverse proxy or on localhost, otherwise none of the app will work. For now, we can just use certbot to get the certificates manually, and pass them as a file. No need to worry about automation for now.

This will be required for #68  and is also a blocker for #65.

**Comment by PenguinSnail** [comment]
HTTPS is now working in the `snapcraft` branch
- The user may specify a location for their key/crt files, or use defaults
- HTTPS can also be disabled with the use of a cli option

Closing as this will be merged in the following few days
