### ISSUE TITLE
Replace GoScout with RustREST

### ISSUE THREAD

**Issue by aidanh010** [triplestrange/StrangeScout#8]
This is the basic blueprint / framework list: https://medium.com/sean3z/building-a-restful-crud-api-with-rust-1867308352d8

**Comment by PenguinSnail** [comment]
This isn't mission critical for IRI, more a streamlining improvement.
Moved to the v0.2 milestone

**Comment by aidanh010** [comment]
Yep that was where it was supposed to be. Updated the milestone descriptions but looks like I forgot to move

**Comment by aidanh010** [comment]
Closing as there will be quite a bit of other changes to make before we even decide about this.

**Comment by aidanh010** [comment]
With proper `go module` support landing with Go 1.11 in August, there's less and less reason to move to Rust. Performance is perfectly acceptable, and we should look into Golang multithreading, but there really aren't any compelling features in Rust to justify the switch. As developing languages, both are racing to add similar features but Go should provide everything we need for now. As long as we can get what we want out of the GORM ORM library, there's nothing really compelling a switch. Can re-evaluate in another year based on language constraints encountered in the future. For now, cancelling this issue.
